GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/61c3583f62fc4432181fe147

###

POST http://localhost:3000/subscribers 
Content-Type: application/json

{
    "name": "Another one",
    "subscribedToChannel": "MichaelGannons Channel"
}

###

DELETE http://localhost:3000/subscribers/61c3583f62fc4432181fe147

###

PATCH http://localhost:3000/subscribers/61c3584c62fc4432181fe149
Content-Type: application/json

{
    "name": "An Amazing Person"
}